### ISSUE TITLE
Not compiled examples

### ISSUE THREAD

**Issue by cmosgh** [LouisBrunner/react-dnd-multi-backend#13]
Hi there. I am struggling with using this with a custom preview component. But for some reason in my case after drag start the preview just gets dropped. Then I can pick it up and finish the drag.

[dnd.mov.zip](https://github.com/LouisBrunner/react-dnd-multi-backend/files/1352049/dnd.mov.zip)

Can you please post the examples in full too?

**Comment by LouisBrunner** [comment]
I am going to look at your issue.

Concerning the source of the examples, they can be found [here](https://github.com/LouisBrunner/react-dnd-multi-backend/tree/master/src/examples).

**Comment by cmosgh** [comment]
Hmm, odd I didn't see that folder. 

Thank you very much.

**Comment by cmosgh** [comment]
Yeap it seems that the issue in my vid was the fact that the dragSource is also a dropTarget

But I don't see another way of doing `hover effects` for placeholders when I am grabbing a source.

Do you have any ideas?

**Comment by LouisBrunner** [comment]
Mmmh... the drag does stop, but only the second time it seems. I remember having this problem, but it may come from the `react-dnd-touch-backend` itself. Do you have some code example I could try? I have a few components that are both DragSource and DropTarget but I haven't seen this problem in a while.

What do you mean by hover effects? Switching around the two blocks when hovering one over the other?

What you could do to avoid having both DragSource and DropTarget on the same element is have a "container" component that represent the slot on the page which would be your DropTarget and the actual block staying the DragSource.

**Comment by cmosgh** [comment]
The issue was that the placeholder object was rerendered. Solved it. Thank you
