### ISSUE TITLE
Default drag layer present when { preview: true } on HTML5Backend

### ISSUE THREAD

**Issue by Tsourdox** [LouisBrunner/react-dnd-multi-backend#19]
**Hello, thx for this cool library!**
I need to make a custom preview/drag-layer for both Touch and HTML5 backends.

**I'm currently using this setup:**
```
const HTML5toTouch = {
    backends: [
        {
            backend: HTML5Backend,
            preview: true,
            transition: HTML5DragTransition
        },
        {
            backend: TouchBackend({enableMouseEvents: false}),
            preview: true,
            transition: TouchTransition
        }
    ]
};
```

**Problem**
The title probably explains it but both the default drag layer and the generated drag layer is visible when dragging with a mouse.

Is that a bug or a feature and any ideas on how to not show the default drag layer? ^^

**Comment by Tsourdox** [comment]
Found the answer here.

https://github.com/react-dnd/react-dnd/blob/master/examples/02%20Drag%20Around/Custom%20Drag%20Layer/DraggableBox.js

```
componentDidMount() {
        // Use empty image as a drag preview so browsers don't draw it
	// and we can draw whatever we want on the custom drag layer instead.
	this.props.connectDragPreview(getEmptyImage(), {
		// IE fallback: specify that we'd rather screenshot the node
		// when it already knows it's being dragged so we can hide it with CSS.
		captureDraggingState: true,
	})
}
```

**Comment by Soundvessel** [comment]
Were you able to use the Preview component for those backends or did you have to separately set up a custom drag layer for `HTML5Backend` (mouse dragging)?
