### ISSUE TITLE
Dependency is missing

### ISSUE THREAD

**Issue by effect305** [LouisBrunner/react-dnd-multi-backend#6]
PureComponent, that is used in `/src/lib/Preview.js`, is appeared only in react 15.3.0 https://github.com/facebook/react/blob/master/CHANGELOG.md#1530-july-29-2016. So I believe you should add dependency to `"react": "^15.3.0"`

**Comment by LouisBrunner** [comment]
Hey,

While it's true that `PureComponent` was introduced in 15.3.0, I chose to use `"react": "*"` so you could use any version of React that you want.
But you are right, using `"react": ">=15.3.0"` would be more correct.
However, I am wondering if the use of `PureComponent` is actually relevant or just a waste of resource.
