### ISSUE TITLE
Error in IE: Object.assign is not a function

### ISSUE THREAD

**Issue by maxcc0** [LouisBrunner/react-dnd-multi-backend#7]
Object.assign is not a function

**Comment by maxcc0** [comment]
Object.assign is not a function

**Comment by LouisBrunner** [comment]
Hi @maxcc0,

At the moment, IE is not supported (I didn't test for it, so I don't know what need to be changed).

However, you can find a fork [here](https://github.com/iFixit/react-dnd-multi-backend) that supports more browsers, albeit with an older version.

Moreover, could you give more context from where you got the error? A stacktrace and usage would be nice.

**Comment by LouisBrunner** [comment]
Fixed by #12
